### ISSUE TITLE
Cannot open .XLS file saved in LibreOffice

### ISSUE THREAD

**Issue by uchti** [extrame/xls#11]
Cannot read .XLS file saved in LibreOffice ( Libreoffice.org ). Same file saved in MS Office reads without problems. I tried to diagnose the problem and it seems to me that problem is in "extrame/ole2" package, but I'm not sure.
I would be grateful if you help fix this problem. 
Thanks.

[Examples XLS.zip](https://github.com/extrame/xls/files/390217/Examples.XLS.zip)

**Comment by extrame** [comment]
fixed, please update xls library and ole2 library to use.
