### ISSUE TITLE
数据量大时会出现错位现象

### ISSUE THREAD

**Issue by gr258** [extrame/xls#25]
当读取较大的excel文件时，出现行列错位现象，经过调试，发现是保存SST – Shared String Table存在bug
1.parseBof函数
case 0x3c: // CONTINUE
...
if size > 0 {
					str, err = wb.get_string(buf_item, size)
					wb.sst[offset_pre] = wb.sst[offset_pre] + str
				}
//此处wb.get_string读取返回EOF的情况下，应该退出循环，否则会导致offset_pre空加，最终导致sst索引错位
				offset_pre++

2.get_string函数
if flag&0x1 != 0 {
...
} else {
...
if uint16(n) < size {
				w.continue_utf16 = size - uint16(n)
				err = io.EOF
			}

			var bts1 = make([]uint16, size)//此处err为EOF的情况下，make的大小应该取n而不是size，否则获取到的字符串会出现多余的0

**Comment by extrame** [comment]
这个offset_pre是用于下一个string的值，我理解应该是任何情况都需要++的，能把示例文件发过来测试一下么？

get_string的问题修正了

**Comment by gr258** [comment]
当string较长时，会被拆到2个CONTINUE段，此时wb.get_string仅获取了该string的部分内容，返回EOF，string剩余的部分在下一个CONTINUE段，此时wb.sst[offset_pre]内保存的内容是不完整的。当解析下一个CONTINUE段时，需要进行拼接：wb.sst[offset_pre] = wb.sst[offset_pre] + str。如果wb.get_string返回EOF时，offset_pre++，那么wb.sst[offset_pre-1]保存的内容就不完整了，一个string被分开存到了2个sst中，造成sst索引错误。

**Comment by extrame** [comment]
got it , fixed
