### ISSUE TITLE
Anything with $ doesn't work 

### ISSUE THREAD

**Issue by posito** [extrame/xls#26]
$ as monetary

**Comment by posito** [comment]
@extrame if you can take a look it would be great

**Comment by extrame** [comment]
could you give me an example xls file for this?

**Comment by posito** [comment]
@extrame https://www.dropbox.com/s/jfzzye5ghywt78o/test.xls?dl=0
If you can take of this soon... That would be amazing.

**Comment by extrame** [comment]
dropbox told me the file was deleted (404 error) @posito

**Comment by posito** [comment]
@extrame can you try it again 

https://www.dropbox.com/s/zxsckiyzjkv1vvs/test.xls?dl=0

**Comment by extrame** [comment]
Oops, dropbox told me that file may be deleted (404)

**Comment by posito** [comment]
This definitely not deleted.
How can i send it to you ?

**Comment by posito** [comment]
I have attached at a zip
[test.zip](https://github.com/extrame/xls/files/1176102/test.zip)

**Comment by extrame** [comment]
Got it from dropbox, ok, it is a problem of decimal format, you use a user defined format for number, I will try to fix it by updating the format method in a new branch, it will need some time to finish it

**Comment by posito** [comment]
thank you. Can you point me in the code where the fix should and do ? and maybe I can take a stab at it... I am badly in need of this fix.. :( I was under the impression that my tool was generating xslx

**Comment by extrame** [comment]
try the new_formatter branch, it is not finished yet, but can print out the number without format
