### ISSUE TITLE
xls parsing not working in master branch

### ISSUE THREAD

**Issue by seaguest** [extrame/xls#32]
Hello,

My xls file is not parsed correctly in master branch, but it works if I changed to new_formatter branch.

here is my code

package main

import (
	"errors"
	"flag"
	"fmt"

	"github.com/extrame/xls"
)

func main() {
	filePath := flag.String("file", "/home/seaguest/Documents/a.xls", "order file")
	flag.Parse()

	err := updateOrderFromFile(*filePath)
	fmt.Println(err)
}

func updateOrderFromFile(path string) error {
	xlFile, err := xls.Open(path, "utf-8")
	if err != nil {
		fmt.Println(err)
		return err
	}

	sheet1 := xlFile.GetSheet(0)
	if sheet1 == nil {
		err := errors.New("empty sheet")
		fmt.Println(err)
		return err
	}

	fmt.Println("Total Lines ", sheet1.MaxRow, sheet1.Name)

	fmt.Println(sheet1)

	for i := 1; i <= int(sheet1.MaxRow); i++ {
		for ci := sheet1.Row(0).FirstCol(); ci < sheet1.Row(0).LastCol(); ci++ {
			fmt.Println(ci)
			fmt.Println("name---", sheet1.Row(0).Col(ci), "---value-------------->>>>", sheet1.Row(i).Col(ci))

			estimatedEffect := sheet1.Row(i).Col(ci)
			fmt.Println(estimatedEffect)
		}
	}
	return nil

Here is my xls file

a
--
8.38
8.38
11.20
3.87

Could anyone explain?

**Comment by extrame** [comment]
yes, new_formatter branch add some new feature of formatting date and number

在 2018年3月18日，15:01，seaguest <notifications@github.com<mailto:notifications@github.com>> 写道：


Hello,

My xls file is not parsed correctly in master branch, but it works if I changed to new_formatter branch.

here is my code

`
package main

import (
"errors"
"flag"
"fmt"

"github.com/extrame/xls<http://github.com/extrame/xls>"


)

func main() {
filePath := flag.String("file", "/home/seaguest/Documents/a.xls", "order file")
flag.Parse()

err := updateOrderFromFile(*filePath)
fmt.Println(err)


}

func updateOrderFromFile(path string) error {
xlFile, err := xls.Open(path, "utf-8")
if err != nil {
fmt.Println(err)
return err
}

sheet1 := xlFile.GetSheet(0)
if sheet1 == nil {
        err := errors.New("empty sheet")
        fmt.Println(err)
        return err
}

fmt.Println("Total Lines ", sheet1.MaxRow, sheet1.Name)

fmt.Println(sheet1)

for i := 1; i <= int(sheet1.MaxRow); i++ {
        for ci := sheet1.Row(0).FirstCol(); ci < sheet1.Row(0).LastCol(); ci++ {
                fmt.Println(ci)
                /*      name := sheet1.Row(0).Col(ci)
                        if name != "预估收入" {
                                continue
                        }*/

                fmt.Println("name---", sheet1.Row(0).Col(ci), "---value-------------->>>>", sheet1.Row(i).Col(ci))

                estimatedEffect := sheet1.Row(i).Col(ci)
                fmt.Println(estimatedEffect)
        }
}
return nil


}

`

Here is my xls file:
`

a

8.38
8.38
11.20
3.87
`

Could anyone explain?
