### ISSUE TITLE
formula Read

### ISSUE THREAD

**Issue by lihui7800** [extrame/xls#41]
dear all:
     when i test read a .xls file,it has some formula cells but the result is "",
  if anyone has method please tell me.

**Comment by extrame** [comment]
get me the example file, I can test it

在 2018年7月2日，11:12，litiehui <notifications@github.com<mailto:notifications@github.com>> 写道：


dear all:
when i test read a .xls file,it has some formula cells but the result is "",
if anyone has method please tell me.
