### ISSUE TITLE
数值读取错误

### ISSUE THREAD

**Issue by flyin9** [extrame/xls#54]
读取-3244847.30  会变成  7492570.94 

 -1184955  -> 1072556869
-1487365  -> 1072254459

**Comment by sergeilem** [comment]
Hello @flyin9. Can you attach your xls file? We will try to reproduce and fix problem. Also you can try this fork: sergeilem/xls.

**Comment by flyin9** [comment]
> Hello @flyin9. Can you attach your xls file? We will try to reproduce and fix problem. Also you can try this fork: https://github.com/sergeilem/xls.


[test.xls.zip](https://github.com/extrame/xls/files/2924509/test.xls.zip)

thanks for your reply

**Comment by flyin9** [comment]
> > Hello @flyin9. Can you attach your xls file? We will try to reproduce and fix problem. Also you can try this fork: https://github.com/sergeilem/xls.
> 
> [test.xls.zip](https://github.com/extrame/xls/files/2924509/test.xls.zip)
> 
> thanks for your reply,fork: https://github.com/sergeilem/xls has the same issue

<img width="741" alt="image" src="https://user-images.githubusercontent.com/3860071/53784398-11cb9900-3f50-11e9-8a14-ddbc8b161b72.png">

将 rk >> 2  改成  int32(rk)>>2 解决问题

**Comment by sergeilem** [comment]
Yes, i also found problem is here. Nice solution. Pushed to github.com/sergeilem/xls.
