### ISSUE TITLE
打开一个小文件，占用19G内存

### ISSUE THREAD

**Issue by wanghu198343** [extrame/xls#92]
调用
`xls.OpenReader`
方法打开文件，文件大小47KB，瞬间用掉19G内存,致使服务器崩溃。
请问有没有什么方法，能判断文件是否正常，或者占用到指定内存，就抛出异常吗？
注：xls文件是通过wps加密了，但程序无法知道用户上传的xls文件是否加密，或者说是否合法。

**Comment by wanghu198343** [comment]
![image](https://github.com/extrame/xls/assets/25630968/68b95d28-b65b-4897-a200-904f3e22c003)
 就是在这个for循环里，消耗了19G内存。go的版本是1.20.6

**Comment by lifenglsf** [comment]
怎么判断出来是加密的？
